# Generated by Django 2.0a1 on 2017-12-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellifprime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numvalue',
            name='number_value',
            field=models.IntegerField(),
        ),
    ]
